services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    command: ["/wait-for-postgres.sh", "db", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./templates:/code/templates
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: celery -A app.celery_config.celery_app worker -l info
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: celery -A app.celery_config.celery_app beat -l info
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: